AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Salimon Netwatch Web Application
Parameters:
  Env:
    Type: String
    Default: "dev"

Resources:
  WebappBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "salimon-netwatch-${Env}"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
  WebappBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebappBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${WebappBucket.Arn}/*"
  CloudFrontRewriteFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: !Sub "rewritespa-netwatch-${Env}"
      AutoPublish: true
      FunctionCode: |
        function handler(event) {
          var request = event.request;
          var uri = request.uri;

          // If path does not contain a file extension, rewrite to /index.html
          if (!uri.includes('.') && !uri.endsWith('/')) {
            request.uri = '/index.html';
          }
          return request;
        }
      FunctionConfig:
        Comment: "Rewrite all SPA routes to index.html"
        Runtime: cloudfront-js-1.0
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt WebappBucket.DomainName
            S3OriginConfig: {}
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # AWS::CloudFront::CachePolicy.CachingOptimized
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt CloudFrontRewriteFunction.FunctionMetadata.FunctionARN
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
